// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs8SThYkByqnEnNhPzWv9rpDbRK6CKkTo',
    appId: '1:1060637668034:web:e02e11427a579b9ede015b',
    messagingSenderId: '1060637668034',
    projectId: 'vocabofinalapp',
    authDomain: 'vocabofinalapp.firebaseapp.com',
    storageBucket: 'vocabofinalapp.firebasestorage.app',
    measurementId: 'G-12XE10LPLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE_EkRXT8ELuaxV9B3JawZmZr-SGZYPd0',
    appId: '1:1060637668034:android:1251eee3136c33b6de015b',
    messagingSenderId: '1060637668034',
    projectId: 'vocabofinalapp',
    storageBucket: 'vocabofinalapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjs5XcFm7oTz6hMd0LpDYXCTMkSW5qmN0',
    appId: '1:1060637668034:ios:e60af2ad6ba0709cde015b',
    messagingSenderId: '1060637668034',
    projectId: 'vocabofinalapp',
    storageBucket: 'vocabofinalapp.firebasestorage.app',
    androidClientId: '1060637668034-r3go25eg8bb8nl1rsenugp6d573l51dl.apps.googleusercontent.com',
    iosClientId: '1060637668034-pj0jrl8l6kt8616mq88cj8gv08kido09.apps.googleusercontent.com',
    iosBundleId: 'com.vocabo.vocabofinalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjs5XcFm7oTz6hMd0LpDYXCTMkSW5qmN0',
    appId: '1:1060637668034:ios:e60af2ad6ba0709cde015b',
    messagingSenderId: '1060637668034',
    projectId: 'vocabofinalapp',
    storageBucket: 'vocabofinalapp.firebasestorage.app',
    androidClientId: '1060637668034-r3go25eg8bb8nl1rsenugp6d573l51dl.apps.googleusercontent.com',
    iosClientId: '1060637668034-pj0jrl8l6kt8616mq88cj8gv08kido09.apps.googleusercontent.com',
    iosBundleId: 'com.vocabo.vocabofinalapp',
  );
}
